apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
spec:
  selector:
    matchLabels:
      app: userjava
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
      - name: userjava
        image: registrykna5332.azurecr.io/tripinsights/user-java:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name:  SQL_USER
            valueFrom:
              secretKeyRef:
                name:  sql-secrets
                key:  SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secrets
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              configMapKeyRef:
                name: userjava-config
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              configMapKeyRef:
                name: userjava-config
                key: SQL_DBNAME
          - name: CONFIG_FILES_PATH
            valueFrom:
              configMapKeyRef:
                key: CONFIG_FILES_PATH
                name: userjava-config

        