kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-full-access
  namespace: tripviewer-apis
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webdev-full-access
  namespace: tripviewer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]