apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrykna5332.azurecr.io/tripinsights/poi:v1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: ""
        - name: SQL_PASSWORD
          value: ""
        - name: SQL_SERVER
          value: ""
        - name: SQL_DBNAME
          value: "mydrivingDB"
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi