apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: poi
        image: imageid registrykna5332.azurecr.io/tripinsights/poi:v1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi