apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  selector:
    app: tripviewer  #must match the labels in the deployment template
  ports:
  - port: 80
    targetPort: 80 #must match the container port of the Pod
  type: LoadBalancer #Use ClusterIP
