apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: tripviewer
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /(.*)
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: tripviewer-apis
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
      paths:
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips/(.*)
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi/(.*)
      - backend:
          serviceName: user
          servicePort: 80
        path: /api/user/(.*)
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java/(.*)
