apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      app: userprofile
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrykna5332.azurecr.io/tripinsights/userprofile:v1.0
        imagePullPolicy: Always
        volumeMounts:
          - name: secrets-kv
            mountPath: "/secrets"
            readOnly: true
        ports:
        - containerPort: 80
        env:
          - name: CONFIG_FILES_PATH
            valueFrom:
              configMapKeyRef:
                key: CONFIG_FILES_PATH
                name: userprofile-config
      volumes:
        - name: secrets-kv
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname
            nodePublishSecretRef:
              name: secrets-store-creds

        