apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  selector:
    app: userprofile  #must match the labels in the deployment template
  ports:
  - port: 80
    targetPort: 80 #must match the container port of the Pod
  type: ClusterIP #Use ClusterIP
